### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by GOlivierNation** [khitermedachraf/Capstone1-TNW-Conference#2]
Hello **@khitermedachraf**  I can see you did an Amazing Job 👌.
**********************************************************************
Professional ReadMe presentation, However, I would like to recommend you to check on the live preview of your project in your ReadMe as it is not being redirected to the Web page.

### **Keep Coding**

*********************************************************************************************************************************************

**Comment by khitermedachraf** [comment]
Okay, thank you so much, Brother @GOlivierNation.
I am working on it to add the **GitHub Pages.**
